//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPL_Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPL_Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap balbash_logo {
            get {
                object obj = ResourceManager.GetObject("balbash_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logo_tevel {
            get {
                object obj = ResourceManager.GetObject("logo_tevel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap madaim {
            get {
                object obj = ResourceManager.GetObject("madaim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ReverseBytes&quot;: true,
        ///  &quot;spl_header&quot;: {
        ///    &quot;ID&quot;: {
        ///      &quot;startByte&quot;: 0,
        ///      &quot;length&quot;: 4
        ///    },
        ///    &quot;Type&quot;: {
        ///      &quot;startByte&quot;: 4,
        ///      &quot;length&quot;: 1
        ///    },
        ///    &quot;Subtype&quot;: {
        ///      &quot;startByte&quot;: 5,
        ///      &quot;length&quot;: 1
        ///    },
        ///    &quot;Length&quot;: {
        ///      &quot;startByte&quot;: 6,
        ///      &quot;length&quot;: 2
        ///    },
        ///    &quot;DataStartingByte&quot;: 8
        ///  },
        ///  &quot;calibrations&quot;: [
        ///    {
        ///      &quot;ID&quot;: &quot;1&quot;,
        ///      &quot;name&quot;: &quot;Temperature&quot;,
        ///      &quot;a&quot;: &quot;0.0009765625&quot;,
        ///      &quot;b&quot;: &quot;0&quot;
        ///    },
        ///    {
        ///      &quot;ID&quot;: &quot;2&quot;,
        ///      &quot;name&quot;: &quot;V [rest of string was truncated]&quot;;.
        /// </summary>
        public static string rx {
            get {
                return ResourceManager.GetString("rx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;endNodePath&quot;: &quot;C:\\Users\\User\\OneDrive\\מסמכים\\projects\\GSC\\endnode\\endnode\\windows\\GSC-EndNode.exe&quot;,
        ///  &quot;enableImage&quot;: false,
        ///  &quot;dataBaseEnabled&quot;: true,
        ///  &quot;tcpPortNumber&quot;: 4,
        ///  &quot;defaultSatGroup&quot;: 2,
        ///  &quot;enableExcel&quot;: true,
        ///  &quot;widgetSettings&quot;: {
        ///    &quot;minThresholdSatPass&quot;: 5
        ///  },
        ///  &quot;serverMode&quot;: &quot;TCP&quot;,
        ///  &quot;UDP_ports&quot;: {
        ///    &quot;client&quot;: 27002,
        ///    &quot;server&quot;: 27002
        ///  },
        ///  &quot;groundStationLocation&quot;: {
        ///    &quot;lat&quot;: 30.983852,
        ///    &quot;lng&quot;: 34.92953,
        ///    &quot;alt&quot;: 500,
        ///    &quot;minElevation&quot;: 1
        ///  },        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ReverseBytes&quot;: false,
        ///  &quot;calibrations&quot;: [
        ///    { &quot;ID&quot;: &quot;mV&quot;, &quot;name&quot;: &quot;Temperature&quot;, &quot;a&quot;: &quot;1&quot;, &quot;b&quot;: &quot;0&quot; },
        ///    { &quot;ID&quot;: &quot;mA&quot;, &quot;name&quot;: &quot;Voltage&quot;, &quot;a&quot;: &quot;1&quot;, &quot;b&quot;: &quot;0&quot; },
        ///    { &quot;ID&quot;: &quot;mW&quot;, &quot;name&quot;: &quot;Voltage&quot;, &quot;a&quot;: &quot;1&quot;, &quot;b&quot;: &quot;0&quot; },
        ///    { &quot;ID&quot;: &quot;deg&quot;, &quot;name&quot;: &quot;Temperature&quot;, &quot;a&quot;: &quot;1&quot;, &quot;b&quot;: &quot;0&quot; },
        ///    { &quot;ID&quot;: &quot;deg c&quot;, &quot;name&quot;: &quot;Temperature&quot;, &quot;a&quot;: &quot;1&quot;, &quot;b&quot;: &quot;0&quot; },
        ///    { &quot;ID&quot;: &quot;dBm&quot;, &quot;name&quot;: &quot;Voltage&quot;, &quot;a&quot;: &quot;1&quot;, &quot;b&quot;: &quot;0&quot; },
        ///    { &quot;ID&quot;: &quot;Hz&quot;, &quot;name&quot;: &quot;Voltage&quot;, &quot;a&quot;: &q....
        /// </summary>
        public static string TauRx {
            get {
                return ResourceManager.GetString("TauRx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ReverseBytes&quot;: true,
        ///  &quot;spl_header&quot;: {
        ///    &quot;ID&quot;: {
        ///      &quot;startByte&quot;: 0,
        ///      &quot;length&quot;: 4
        ///    },
        ///    &quot;Type&quot;: {
        ///      &quot;startByte&quot;: 4,
        ///      &quot;length&quot;: 1
        ///    },
        ///    &quot;Subtype&quot;: {
        ///      &quot;startByte&quot;: 5,
        ///      &quot;length&quot;: 1
        ///    },
        ///    &quot;Length&quot;: {
        ///      &quot;startByte&quot;: 6,
        ///      &quot;length&quot;: 2
        ///    },
        ///    &quot;DataStartingByte&quot;: 8
        ///  },
        ///  &quot;types&quot;: [
        ///    {
        ///      &quot;id&quot;: &quot;0&quot;,
        ///      &quot;name&quot;: &quot;TRXVU&quot;,
        ///      &quot;desc&quot;: &quot;All TRXVU function calls&quot;,
        ///      &quot;subtypes&quot;: [
        ///        {
        ///          &quot;id&quot;: &quot;166&quot;,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tx {
            get {
                return ResourceManager.GetString("tx", resourceCulture);
            }
        }
    }
}
